%% LaBGAS_copy_single_trial_con_imgs_CANlab_folder_struct
%
% This simple script copies all single trial con images from
% rootdir\firstlevel\model_x_yyy\sub-zz\ to
% rootdir\secondlevel\model_x_yyy\con_images\sub-zz
% to prepare second level analysis with CANlab batch scripts
%
% Con images include
% 1. con_0001-3 defined in LaBGAS_get_single_trial_dsgn_obj.m and created
%    by LaBGAS_2_spm_fit_firstlvl_models.m
%    These are the 3 con images per subject for the negative, neutral, and 
%    positive condition over all single trials, hence similar to 
%    con images generated by classic GLM
% 2. con_0007:end defined and created by LaBGAS_add_single_trial_contrasts.m
%    These are 2 con images per condition per run, for each single trial,
%    ordered per condition: negative, neutral, positive
%
%__________________________________________________________________________
%
% author: lukas.vanoudenhove@kuleuven.be
% date:   March, 2021
%__________________________________________________________________________
% @(#)% LaBGAS_copy_single_trial_con_imgs_CANlab_folder_struct     v1.0        
% last modified: 2021/03/22

%% define model and directories
model='model_2_CANlab_single_trial_GLM';
rootdir='C:\Users\lukas\Dropbox (Dartmouth College)\fMRI_emotion_Giao\BIDS';
firstleveldir=fullfile(rootdir,'firstlevel\',model);
secondleveldir=fullfile(rootdir,'secondlevel\',model);
if ~isfolder(secondleveldir)
    mkdir(secondleveldir);
end
conimgsdir=fullfile(secondleveldir,'\data');
if ~isfolder(conimgsdir)
    mkdir(conimgsdir);
end

%% get subject directory names from firstleveldir
subjs = dir([firstleveldir,'\sub-*']);
subjs = {subjs(:).name}';

%% define anonymous function sm to write folder structure with cell array of folder names as input
sm=@(x)spm_mkdir(x); % defines spm_mkdir as an anonymous function sm

%% write folder structure in conimgsdir
cd(conimgsdir);
cellfun(sm,subjs); % applies function sm to all cells of subjs

%% loop over subjects to copy the relevant con images over
for i=1:size(subjs,1)
    subjfirstleveldir=fullfile(firstleveldir,subjs{i});
    subjconimgsdir=fullfile(conimgsdir,subjs{i});
    cd(subjfirstleveldir);
    conimgs=ls('con*.nii');
    conimgs2copy = [conimgs(1:3,:);conimgs(7:end,:)];
        for j=1:size(conimgs2copy,1)
            copyfile(fullfile(subjfirstleveldir,conimgs2copy(j,:)),fullfile(subjconimgsdir,conimgs2copy(j,:)));
        end
end